### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by jamesnesfield** [peekabustudios/generator-angular-frontend#1]
'yo angular-frontend dawnchorus'  

after 

'npm install -g generator-angular-frontend' 

gives

'You don't seem to have a generator with the name angular-frontend installed.'

**Comment by aitk** [comment]
I'll take a look at that 👍

**Comment by aitk** [comment]
Sorry for taking so long. The generator in yeoman is ng-jade-less so the command is `yo ng-jade-less`
